### ISSUE TITLE
Please publish wheels for Python 3.10 

### ISSUE THREAD

**Issue by gertvdijk** [ColdHeat/pybluemonday#29]
Using a Python 3.10 venv upgraded from 3.9, pip grabs a source package and requires me to have Go SDK installed on the target system. Could you please also build and publish wheels for 3.10? Thanks!

**Comment by ColdHeat** [comment]
I will get to this but if you were to put up a PR that adds 3.10 to cibuildwheel that would be helpful as well!

**Comment by ColdHeat** [comment]
Actually looking at this, this is probably due to not having a version bump to trigger a new release. Sounds like a good time to update bluemonday as well.

**Comment by ColdHeat** [comment]
This should be resolved now.

**Comment by gertvdijk** [comment]
Hi,

Thanks for picking this up, but this seems incomplete. Wheels are only provided for i686 and aarch64, not for the most common one: x86_64. cp39 has even five architechtures supported.
![Screenshot_20220216_031327](https://user-images.githubusercontent.com/1550527/154183503-1e341870-3a80-4581-81fc-a09b93c9b408.png)

Not sure I understand the CI pipeline here and the matrix in order to help out, I'm not familiar with the tooling used here, sorry, there seem many layers of indirections and I am unfamiliar with all of them (GitHub actions, the 'cibuildwheel' project, etc.)

**Comment by ColdHeat** [comment]
Interesting, thanks for noticing I just assumed this would work but I will take a deeper look.

**Comment by ColdHeat** [comment]
<img width="806" alt="image" src="https://user-images.githubusercontent.com/166333/154331731-f408ba86-bc49-4bc4-af01-1d51a31e7491.png">

I believe this should be good now.

**Comment by gertvdijk** [comment]
It is working, thanks! 👍🏼
